### ISSUE TITLE
Setting time with buttons

### ISSUE THREAD

**Issue by ghost** [Pakue95/VFD_Watch#1]
Hi!

I love the project but I'm not very familiar with c++. 
Looking through the code there is no obvious way to set the time without WIFI.
Could you please describe a way I could use the buttons to set the time rather than needing to be attached to WIFI?

Regards, 
Ollie

**Comment by Pakue95** [comment]
Hey Ollie,

Thank!

I use the ESP32 [internal system time](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html?highlight=settimeofday), which is set via NTP, to track the time. You can set is manually if you want with settimeofday() or use a library like this [one](https://www.arduinolibraries.info/libraries/esp32-time).
[Here](https://github.com/Pakue95/VFD_Watch/blob/a7a951d7522ca1ebe2ff7beca40939c133f14d9f/Code/src/main.cpp#L64) is where the time is set and written to the display if you want to have a go at it.

I might be able to implement something over the weekend to set the time with the buttons.

**Comment by ghost** [comment]
Thankyou that would be interesting to see! i dont know C++ yet so i wouldn't even know to start. but i basically started to write the software again in python as a learning exercise. 
I saw there were some python files in the code folder but it was just an empty file. any reason for this? or was it ssomething you were going to work on?

**Comment by Pakue95** [comment]
I added a bit of code to set the time with the buttons once the wifi connection fails for a few seconds. Left/Right -> up/down; middle -> set the minutes/finish.

I created the python folder for playing around with [MicroPython](https://micropython.org), but never pushed the code due to some bug with mapping I2C to the pins I had chosen.

**Comment by ghost** [comment]
Okay nice, I'll have a look. I actually got it working with micropython today but the i2c does seem a little slow to update I'm not sure why but it might be the library I'm using.
